apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-ci-deployment
spec:
  selector:
    matchLabels: 
      app: flask-ci
  replicas: 1
  template:
    metadata: 
      labels:
        app: flask-ci
    spec:
      containers:
      - name: flask-ci-container
        image: back2
        imagePullPolicy: IfNotPresent
        ports: 
        - containerPort: 10002
      imagePullSecrets:
      - name: regcred 
---
apiVersion: v1
kind: Service
metadata:
  name: flask-ci-service
spec:
  type: ClusterIP
  ports:
  - port: 10002
    targetPort: 10002
    protocol: TCP
  selector: 
    app: flask-ci
 